[features]
gc_debug = [] # Enable debug output for the garbage collector

[package]
name = "rusp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.7.2"
